### ISSUE TITLE
How to install packages using non-pip method in read the docs

### ISSUE THREAD

**Issue by pinggao187** [sumanthratna/viewmask#39]
I have some troubles when using read the docs, please help me, 
I want to install a package, but I can't use pip to install it. In the local python environment, I solved it by downloading the package and adding it to the pythonpath. How to install packages using non-pip method in read the docs?

**Comment by sumanthratna** [comment]
Hey @pinggao187! I think I would either fork or push a PR to the package adding a `setup.py`. If you fork, you can upload the package to PyPI and then pip install it. If you don't want to push to PyPI, then you can add `git+https://github.com/pinggao187/my-package@master#egg=sphinx-click` to `requirements.txt` (but I would recommend pinning to a specific branch/tag instead of `master`). 

I hope this helped!
